# Generated by Django 4.1 on 2022-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('question_no', models.IntegerField()),
                ('answer1_count', models.IntegerField()),
                ('answer2_count', models.IntegerField()),
                ('answer3_count', models.IntegerField()),
                ('answer4_count', models.IntegerField()),
                ('total_answer', models.IntegerField()),
            ],
        ),
    ]
